import { PageContainer } from '@/features/dashboard/components/PageContainer';
import { PlatformDetails, PlatformEmptyState, PlatformErrorState, PlatformMetricGrid, PlatformSearchParams, PlatformStatusBadge, PlatformSurface, PlatformToolbar, PlatformTruthNotice, humanize, queryValue } from '@/features/platform/components/PlatformPrimitives';
import { TaskButton } from '@/features/platform/components/TaskButton';
import { platformProjections } from '@/features/platform/lib/platformProjections';
import { updateCouponTask } from '@/features/platform/lib/taskActions';

function dateLabel(value?: string | null) { return value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(value)) : 'No date'; }
function money(cents = 0, currencyCode = 'USD') { return new Intl.NumberFormat('en-US', { style: 'currency', currency: currencyCode || 'USD' }).format(cents / 100); }

export async function MerchandisingPage({ searchParams }: { searchParams?: Promise<PlatformSearchParams> | PlatformSearchParams } = {}) {
  const params = searchParams ? await searchParams : {};
  const q = queryValue(params, 'q').trim().toLowerCase();
  const filter = queryValue(params, 'filter') || 'all';
  const sort = queryValue(params, 'sort') || 'sort_order';
  let data: Awaited<ReturnType<typeof platformProjections.merchandising>> = null;
  let loadError: string | null = null;
  try { data = await platformProjections.merchandising(); } catch (error) { loadError = error instanceof Error ? error.message : 'Unable to load merchandising.'; }
  const currencyCode = data?.currencyCode || 'USD';
  const departments = [...(data?.departments || [])].filter((department) => !q || department.name.toLowerCase().includes(q) || department.handle.toLowerCase().includes(q)).filter((department) => filter !== 'departments_inactive' || !department.isActive).sort((a, b) => sort === 'products' ? b.products.length - a.products.length : sort === 'name' ? a.name.localeCompare(b.name) : Number(a.sortOrder || 0) - Number(b.sortOrder || 0));
  const coupons = [...(data?.coupons || [])].filter((coupon) => !q || coupon.code.toLowerCase().includes(q) || coupon.productCategories?.some((category) => category.toLowerCase().includes(q))).filter((coupon) => filter === 'all' || filter === 'departments_inactive' || (filter === 'active' ? coupon.isActive : filter === 'exhausted' ? coupon.maxUses > 0 && coupon.currentUses >= coupon.maxUses : !coupon.isActive)).sort((a, b) => sort === 'usage' ? b.currentUses - a.currentUses : sort === 'expiry' ? String(a.validTo || '9999').localeCompare(String(b.validTo || '9999')) : a.code.localeCompare(b.code));
  const activeCoupons = (data?.coupons || []).filter((coupon) => coupon.isActive).length;
  const exhausted = (data?.coupons || []).filter((coupon) => coupon.maxUses > 0 && coupon.currentUses >= coupon.maxUses).length;
  const inactiveDepartments = (data?.departments || []).filter((department) => !department.isActive).length;
  const breadcrumbs = [{ type: 'link' as const, label: 'Dashboard', href: '/dashboard' }, { type: 'page' as const, label: 'Platform' }, { type: 'page' as const, label: 'Merchandising' }];
  const header = <div><h1 className="text-2xl font-semibold tracking-tight">Merchandising</h1><p className="mt-1 text-sm text-muted-foreground">Audit department storefront readiness and the bounded single-coupon promotion surface.</p></div>;

  return <PageContainer title="Merchandising" header={header} breadcrumbs={breadcrumbs}><div className="space-y-5 px-4 pb-8 md:px-6">
    <PlatformMetricGrid metrics={[{ label: 'Active departments', value: (data?.departments.length || 0) - inactiveDepartments, note: `${inactiveDepartments} inactive` }, { label: 'Catalog relationships', value: (data?.departments || []).reduce((sum, department) => sum + department.products.length, 0), note: 'Department → product links' }, { label: 'Active coupons', value: activeCoupons, note: 'Checkout still accepts at most one coupon' }, { label: 'Exhausted coupons', value: exhausted, note: 'Current uses reached configured maximum', tone: exhausted ? 'warning' : 'default' }]} />
    <PlatformTruthNotice title="Promotion boundary">Coupon qualification is Store-scoped and cent-exact, but line allocation, stacking priority, supplier funding, loyalty earn/burn, and promotion settlement are not implemented.</PlatformTruthNotice>
    <PlatformToolbar search={q} searchPlaceholder="Department, handle, coupon, or category" filter={filter} filterLabel="View" filterOptions={[{ value: 'all', label: 'All merchandising' }, { value: 'active', label: 'Active coupons' }, { value: 'inactive', label: 'Inactive coupons' }, { value: 'exhausted', label: 'Exhausted coupons' }, { value: 'departments_inactive', label: 'Inactive departments' }]} sort={sort} sortOptions={[{ value: 'sort_order', label: 'Department order / coupon code' }, { value: 'name', label: 'Name A–Z' }, { value: 'products', label: 'Most products' }, { value: 'usage', label: 'Most coupon uses' }, { value: 'expiry', label: 'Coupon expiry soonest' }]} resultCount={departments.length + coupons.length} />
    {loadError ? <PlatformErrorState description={loadError} /> : <div className="grid gap-5 xl:grid-cols-2">
      <PlatformSurface title="Departments" description="Storefront grouping, display order, and temperature-zone labels.">{departments.length === 0 ? <PlatformEmptyState title="No matching departments" description="Reset the current filters." /> : <div className="divide-y">{departments.map((department) => <PlatformDetails key={department.id} summary={<div className="grid gap-2 px-4 py-4 hover:bg-muted/30 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center md:px-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{department.name}</p><PlatformStatusBadge status={department.isActive ? 'active' : 'cancelled'} label={department.isActive ? 'Active' : 'Inactive'} /></div><p className="truncate text-xs text-muted-foreground">/{department.handle} · {humanize(department.temperatureZone)}</p></div><div className="sm:text-right"><p className="font-semibold tabular-nums">{department.products.length}</p><p className="text-xs text-muted-foreground">products · sort {department.sortOrder ?? 0}</p></div></div>}><p className="text-sm text-muted-foreground">Department edits remain in the diagnostic model because no bounded merchandising write action exists for this surface.</p></PlatformDetails>)}</div>}</PlatformSurface>
      <PlatformSurface title="Coupons" description="Dates, usage, category predicates, cent authority, and safe activation state.">{coupons.length === 0 ? <PlatformEmptyState title="No matching coupons" description="Reset the current filters." /> : <div className="divide-y">{coupons.map((coupon) => {
        const atLimit = coupon.maxUses > 0 && coupon.currentUses >= coupon.maxUses;
        return <PlatformDetails key={coupon.id} summary={<div className="grid gap-3 px-4 py-4 hover:bg-muted/30 sm:grid-cols-[minmax(0,1fr)_auto_auto] sm:items-center md:px-5"><div><p className="font-mono font-semibold">{coupon.code}</p><p className="text-xs text-muted-foreground">{humanize(coupon.discountType)} · minimum {money(coupon.minPurchaseCents, currencyCode)}</p></div><PlatformStatusBadge status={atLimit ? 'failed' : coupon.isActive ? 'active' : 'cancelled'} label={atLimit ? 'Use limit reached' : coupon.isActive ? 'Active' : 'Inactive'} /><div className="sm:text-right"><p className="font-semibold">{coupon.discountType === 'percentage' ? `${coupon.discountValue || 0}%` : money(coupon.discountValueCents, currencyCode)}</p><p className="text-xs text-muted-foreground">{coupon.currentUses}/{coupon.maxUses || '∞'} uses</p></div></div>}>
          <div className="grid gap-4 sm:grid-cols-2"><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Valid from</dt><dd className="mt-1 font-medium">{dateLabel(coupon.validFrom)}</dd></div><div><dt className="text-xs text-muted-foreground">Valid to</dt><dd className="mt-1 font-medium">{dateLabel(coupon.validTo)}</dd></div><div className="col-span-2"><dt className="text-xs text-muted-foreground">Category predicates</dt><dd className="mt-1 font-medium">{coupon.productCategories?.join(', ') || 'All categories'}</dd></div></dl><div className="flex items-start justify-end"><TaskButton label={coupon.isActive ? 'Pause coupon' : 'Activate coupon'} successLabel={coupon.isActive ? 'Coupon paused' : 'Coupon activated'} onRun={updateCouponTask.bind(null, coupon.id, !coupon.isActive)} /></div></div>
        </PlatformDetails>;
      })}</div>}</PlatformSurface>
    </div>}
  </div></PageContainer>;
}

export default MerchandisingPage;
