import Link from 'next/link';
import { PageContainer } from '@/features/dashboard/components/PageContainer';
import { PlatformDetails, PlatformEmptyState, PlatformErrorState, PlatformMetricGrid, PlatformSearchParams, PlatformStatusBadge, PlatformSurface, PlatformToolbar, PlatformTruthNotice, humanize, queryValue } from '@/features/platform/components/PlatformPrimitives';
import { platformProjections } from '@/features/platform/lib/platformProjections';
import { OrderAfterSalesActions } from '@/features/platform/orders/components/OrderAfterSalesActions';

function money(cents = 0, currencyCode = 'USD') { return new Intl.NumberFormat('en-US', { style: 'currency', currency: currencyCode || 'USD' }).format(cents / 100); }
function dateTime(value?: string | null) { return value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }

export async function PaymentsPage({ searchParams }: { searchParams?: Promise<PlatformSearchParams> | PlatformSearchParams } = {}) {
  const params = searchParams ? await searchParams : {};
  const q = queryValue(params, 'q').trim().toLowerCase();
  const filter = queryValue(params, 'filter') || 'attention';
  const sort = queryValue(params, 'sort') || 'newest';
  let data: Awaited<ReturnType<typeof platformProjections.payments>> = null;
  let loadError: string | null = null;
  try { data = await platformProjections.payments(); } catch (error) { loadError = error instanceof Error ? error.message : 'Unable to load payments.'; }
  const all = data?.payments || [];
  const payments = [...all]
    .filter((payment) => !q || payment.id.toLowerCase().includes(q) || payment.providerCode.toLowerCase().includes(q) || payment.providerPaymentId?.toLowerCase().includes(q) || String(payment.order.displayId).includes(q))
    .filter((payment) => filter === 'all' || (filter === 'attention' ? payment.status === 'failed' || payment.status === 'processing' || payment.refunds.some((refund) => refund.status === 'failed' || refund.reconciliationDeadLetterAt) : filter === 'refunds' ? payment.refunds.length > 0 : payment.status === filter))
    .sort((a, b) => sort === 'amount' ? b.amountCents - a.amountCents : sort === 'oldest' ? a.createdAt.localeCompare(b.createdAt) : b.createdAt.localeCompare(a.createdAt));
  const deadLetters = all.reduce((sum, payment) => sum + payment.refunds.filter((refund) => refund.reconciliationDeadLetterAt).length, 0);
  const currencyCode = data?.currencyCode || 'USD';
  const breadcrumbs = [{ type: 'link' as const, label: 'Dashboard', href: '/dashboard' }, { type: 'page' as const, label: 'Platform' }, { type: 'page' as const, label: 'Payments' }];
  const header = <div><h1 className="text-2xl font-semibold tracking-tight">Payments & refunds</h1><p className="mt-1 text-sm text-muted-foreground">Inspect provider configuration truth, captured money, refund evidence, retries, and dead-letter attention.</p></div>;

  return <PageContainer title="Payments" header={header} breadcrumbs={breadcrumbs}><div className="space-y-5 px-4 pb-8 md:px-6">
    <PlatformMetricGrid metrics={[{ label: 'Captured', value: money(data?.summary.capturedCents, currencyCode), note: `${data?.summary.paymentCount || 0} payment records` }, { label: 'Refunded', value: money(data?.summary.refundedCents, currencyCode), note: 'Succeeded refund evidence' }, { label: 'Net payment evidence', value: money(data?.summary.netCents, currencyCode), note: 'Captured less succeeded refunds' }, { label: 'Needs attention', value: (data?.summary.failedCount || 0) + (data?.summary.processingCount || 0) + deadLetters, note: `${deadLetters} dead-letter refunds`, tone: (data?.summary.failedCount || data?.summary.processingCount || deadLetters) ? 'critical' : 'default' }]} />
    <PlatformTruthNotice title="Money truth surface">Provider installation and runtime configuration are reported separately. This screen does not claim live Stripe card/3DS acceptance, settlement-file reconciliation, disputes, cash close, or bank/GL balancing.</PlatformTruthNotice>
    {loadError ? <PlatformErrorState description={loadError} /> : <>
      <PlatformSurface title="Provider readiness" description="Configuration evidence from the static adapter registry and current runtime—not a synthetic health claim.">
        {(data?.providers || []).length === 0 ? <PlatformEmptyState title="No payment providers" description="No registered provider configuration is visible." /> : <div className="grid gap-px bg-border sm:grid-cols-2 xl:grid-cols-3">{data?.providers.map((provider) => <div key={provider.id} className="bg-background p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{provider.name}</p><p className="font-mono text-xs text-muted-foreground">{provider.code}</p></div><PlatformStatusBadge status={provider.runtimeConfigured ? 'active' : provider.isInstalled ? 'processing' : 'failed'} label={provider.runtimeConfigured ? 'Runtime configured' : provider.isInstalled ? 'Installed · config missing' : 'Not installed'} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-muted-foreground">Adapter</dt><dd className="mt-1 font-medium">{provider.isInstalled ? 'Registered' : 'Unavailable'}</dd></div><div><dt className="text-muted-foreground">Public checkout</dt><dd className="mt-1 font-medium">{provider.publicCheckout ? 'Enabled' : 'Not exposed'}</dd></div></dl></div>)}</div>}
        {Object.keys(data?.summary.recovery || {}).length ? <div className="border-t p-4"><p className="text-xs font-medium text-muted-foreground">Recovery state counts</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(data?.summary.recovery || {}).map(([state, count]) => <span key={state} className="rounded-full border px-2.5 py-1 text-xs"><span className="capitalize">{humanize(state)}</span> · <strong className="tabular-nums">{count}</strong></span>)}</div></div> : null}
      </PlatformSurface>
      <PlatformToolbar search={q} searchPlaceholder="Order, payment ID, provider ID, or code" filter={filter} filterLabel="Payment state" filterOptions={[{ value: 'attention', label: 'Needs attention' }, { value: 'all', label: 'All payments' }, { value: 'succeeded', label: 'Succeeded' }, { value: 'processing', label: 'Processing' }, { value: 'failed', label: 'Failed' }, { value: 'partially_refunded', label: 'Partially refunded' }, { value: 'refunded', label: 'Refunded' }, { value: 'refunds', label: 'Has refund evidence' }]} sort={sort} sortOptions={[{ value: 'newest', label: 'Newest first' }, { value: 'oldest', label: 'Oldest first' }, { value: 'amount', label: 'Highest amount' }]} resultCount={payments.length} />
      <PlatformSurface title="Payment evidence" description="Expand a row for provider identifiers, refund attempts, bounded recovery state, and a valid refund action.">
        {payments.length === 0 ? <PlatformEmptyState title="No matching payments" description="No payment evidence matches the current controls." /> : <div className="divide-y">{payments.map((payment) => {
          const succeededRefunds = payment.refunds.filter((refund) => refund.status === 'succeeded').reduce((sum, refund) => sum + refund.amountCents, 0);
          const hasAttention = payment.status === 'failed' || payment.status === 'processing' || payment.refunds.some((refund) => refund.status === 'failed' || refund.reconciliationDeadLetterAt);
          return <PlatformDetails key={payment.id} summary={<div className="grid gap-3 px-4 py-4 hover:bg-muted/30 md:grid-cols-[minmax(0,1fr)_auto_auto] md:items-center md:px-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">Order #{payment.order.displayId}</p><PlatformStatusBadge status={payment.status} /></div><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{payment.providerCode} · {payment.providerPaymentId || `payment …${payment.id.slice(-8)}`}</p></div><div className="text-sm md:text-right"><p className="font-semibold tabular-nums">{money(payment.amountCents, currencyCode)}</p><p className="text-xs text-muted-foreground">{money(succeededRefunds, currencyCode)} refunded</p></div><PlatformStatusBadge status={hasAttention ? 'failed' : 'active'} label={hasAttention ? 'Review' : 'No recovery alert'} /></div>}>
            <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(19rem,.7fr)]"><div className="space-y-4"><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">Created</dt><dd className="mt-1 font-medium">{dateTime(payment.createdAt)}</dd></div><div><dt className="text-xs text-muted-foreground">Processed</dt><dd className="mt-1 font-medium">{dateTime(payment.processedAt)}</dd></div><div><dt className="text-xs text-muted-foreground">Method</dt><dd className="mt-1 font-medium">{humanize(payment.paymentMethod)}</dd></div></dl>{payment.errorMessage ? <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{payment.errorMessage}</p> : null}
              <div><h3 className="text-sm font-semibold">Refund evidence</h3>{payment.refunds.length === 0 ? <p className="mt-2 text-sm text-muted-foreground">No refund has been requested.</p> : <div className="mt-2 space-y-2">{payment.refunds.map((refund) => <div key={refund.id} className="rounded-lg border bg-background p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium tabular-nums">{money(refund.amountCents, currencyCode)}</span><PlatformStatusBadge status={refund.reconciliationDeadLetterAt ? 'failed' : refund.status} label={refund.reconciliationDeadLetterAt ? 'Dead letter' : undefined} /></div><p className="mt-1 text-xs text-muted-foreground">{refund.reason || 'No reason recorded'} · {refund.reconciliationAttempts} reconciliation attempts</p>{refund.reconciliationLastError || refund.failureMessage ? <p className="mt-2 text-xs text-destructive">{refund.reconciliationLastError || refund.failureMessage}</p> : null}{refund.reconciliationNextAttemptAt ? <p className="mt-1 text-xs text-muted-foreground">Next retry {dateTime(refund.reconciliationNextAttemptAt)}</p> : null}</div>)}</div>}</div>
              <Link href={`/dashboard/payments/${payment.id}`} className="inline-flex min-h-9 items-center rounded-md border px-3 text-xs font-medium hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Open diagnostic payment model</Link>
            </div><OrderAfterSalesActions orderId={payment.order.id} orderStatus={payment.order.status} payments={[payment]} currencyCode={currencyCode} /></div>
          </PlatformDetails>;
        })}</div>}
      </PlatformSurface>
    </>}
  </div></PageContainer>;
}

export default PaymentsPage;
